version: "3.8"
services:
  kuzco-main:
    container_name: kuzco-main
    build: .
    networks:
      - kuzco-network
    restart: always
    environment:
      NODE_ENV: "production"
      CODE: "YOUR_WORKER_CODE"
      VIKEY_API_KEY: "YOUR_VIKEY_API_KEY"
      GPU0_NAME: "NVIDIA GeForce RTX 4090"

networks:
  kuzco-network:
    driver: bridge
