version: "3.8"
services:
  kuzco-main:
    container_name: kuzco-main
    build: .
    networks:
      - kuzco-network
    restart: always
    environment:
      NODE_ENV: "production"
      KUZCO_WORKER: "YOUR_WORKER_ID"
      KUZCO_CODE: "YOUR_WORKER_CODE"
      CACHE_DIRECTORY: "/app/cache"

networks:
  kuzco-network:
    driver: bridge
